.TH PLATER "9" "December 2012" "printrun" "User Commands"
.SH NAME
plater \- Host software for the RepRap 3d printer - gui program to create platers
.SH SYNOPSIS
.B plater
.br
printrun home page: <http://reprap.org/wiki/Printrun>
.br
.SH COPYRIGHT
Copyright \(co 2012 Kliment <https://github.com/kliment>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
