.TH PRONSOLE "9" "December 2012" "laserboy" "User Commands"
.SH NAME
pronsole \- Host software for the RepRap 3d printer - interactive command-line host software with tabcompletion goodness
.SH SYNOPSIS
.B pronsole
.br
printrun home page: <http://reprap.org/wiki/Printrun>
.br
.SH COPYRIGHT
Copyright \(co 2012 Kliment <https://github.com/kliment>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
